image: ubuntu:20.04

before_script:
- apt-get update
- apt-get install -y --no-install-recommends git python3-pip python3-dev python3-virtualenv redis

tests:
  stage: test
  script:
  - ./qa.sh
  only:
  - branches
